In [2]:
import numpy as np

### 01 np.array()

In [3]:
# 1차원 배열

vec = np.array([1, 2, 3, 4, 5])
print(vec)

[1 2 3 4 5]


In [4]:
# 2차원 배열 (array안에 리스트 안에 리스트 생성)

mat = np.array([[10, 20, 30], [60, 70, 100]])
print(mat)

[[ 10  20  30]
 [ 60  70 100]]


In [5]:
print("vec의 타입 : ", type(vec))
print("mat의 타입 : ", type(mat))

vec의 타입 :  <class 'numpy.ndarray'>
mat의 타입 :  <class 'numpy.ndarray'>


In [7]:
# numpy배열에서는 축의 갯수(ndim)과 크기(shape) 개념 존재,
# 배열의 크기를 정확하게 숙지하는 것이 중요하다.

print("vec의 축의 갯수 : ", vec.ndim)
print("vec의 크기(shape) : ", vec.shape)

print(f"mat의 축의 갯수 : {mat.ndim}")
print(f"mat의 크기(shape) : {mat.shape}")

vec의 축의 갯수 :  1
vec의 크기(shape) :  (5,)
mat의 축의 갯수 : 2
mat의 크기(shape) : (2, 3)


### 02 ndarray의 초기화

In [9]:
# 모든 값이 0인 2x3배열 생성

zero_mat = np.zeros((2, 3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 모든 값이 1인 2x3배열 생성

one_mat = np.ones((2, 3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# 특정 상수 지정 배열

full_mat = np.full((2, 3), 7)
print(full_mat)

[[7 7 7]
 [7 7 7]]


In [13]:
# 대각선은 1이고 나머지는 0인 배열

eye_mat = np.eye(5)
print(eye_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# 임의의 값을 가지는 배열

random_mat = np.random.random((2, 3))
print(random_mat)

[[0.898747   0.82709366 0.71725064]
 [0.17029713 0.38652344 0.13340347]]


03 np.arange()

In [24]:
# np.arange()는 0부터 n-1까지의 값을 가지는 배열 생성

range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# np.arange(i, j, k) : i부터 j-1까지 k만큼 증가

n = 2
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

[1 3 5 7 9]


### 04 np.reshape()

In [30]:
# np.reshape() : 배열의 구조를 바꾼다.

reshape_mat = np.array(np.arange(30)).reshape((5, 6))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 05 numpy 슬라이싱

In [32]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [33]:
# 첫 번째 행 출력

slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [34]:
# 두 번째 열 출력

slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


### 06 numpy 정수 인덱싱

In [36]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [37]:
# 1행 0열 원소
# => 0부터 카운트하므로 두번째 행 첫번째 열의 원소
print(mat[1, 0])

4


In [41]:
# 특정 위치의 원소 두 개를 가져와 새로운 배열 만들기
# mat[[행1, 행2], [열1, 열2]]

print(mat[[2, 0], [1, 1]])

[8 2]


### 07 numpy 연산

In [42]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [44]:
result = x + y # np.add와 동일
add = np.add(x, y)

print(result)
print(add)

[5 7 9]
[5 7 9]


In [46]:
result = x - y # np.subtract와 동일
sub = np.subtract(x, y)

print(result)
print(sub)

[-3 -3 -3]
[-3 -3 -3]


In [48]:
result = x * y # np.multiply와 동일
mul = np.multiply(x, y)

print(result)
print(mul)

[ 4 10 18]
[ 4 10 18]


In [49]:
result = x / y # np.divide와 동일
div = np.divide(x, y)

print(result)
print(div)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
